API/urls.py
from django.contrib import admin
from django.urls import path
from API import views

app_name = 'API'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name="home"),
    path('search/', views.SearchView.as_view(), name="search")
]

API_science/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('API.urls', namespace='main')),
]

API/models.py
from django.db import models


class TypesOfWork(models.Model):

    type = models.CharField(unique=True, blank=False, null=False, verbose_name='Тип публикации')


    class Meta():
        db_table = 'TypesOfWorks'
        verbose_name = 'Тип научной работы'
        verbose_name_plural = 'Типы научных работ'

    def __str__(self):
        return self.type


class AuthorNames(models.Model):
    author_name = models.CharField(max_length=50, null=False, blank=False, verbose_name='Имя')
    author_last_name = models.CharField(max_length=50, null=False, blank=False, verbose_name='Фамилия')
    author_middle_name = models.CharField(max_length=50, null=True, blank=True, verbose_name='Отчество')
    other_authors = models.TextField(blank=True, null=True, verbose_name='Имена соавторов')

    class Meta():
        db_table = 'AuthorNames'
        verbose_name = 'Автор'
        verbose_name_plural = 'Имена всех авторов'

    def __str__(self):
        return f"{self.pk} - {self.author_last_name}"

    def full_author_name(self):
        if self.author_middle_name:
            return f"{self.author_last_name.lower().capitalize()} {self.author_name[0]}. {self.author_middle_name[0]}."
        return f"{self.author_last_name.lower().capitalize()} {self.author_name[0]}."
    

class IntelForScienceWorks(models.Model):

    title = models.CharField(max_length=250, null=False, verbose_name='Название')
    annotation = models.TextField(null=True, blank=True, verbose_name='Аннотация')
    OECD = models.CharField(max_length=250, blank=False, null=False, verbose_name='OECD')
    key_words = models.CharField(max_length=500, blank=True, null=True, verbose_name='Ключевые слова')
    year_publication = models.IntegerField(blank=False, null=False, verbose_name='Год публикации')
    work_type_name = models.CharField(max_length=300, blank=False, null=False, verbose_name='Название источника')
    type_of_work = models.ForeignKey(to=TypesOfWork, on_delete=models.CASCADE, verbose_name='Категория')
    authors = models.ForeignKey(to=AuthorNames, on_delete=models.CASCADE, verbose_name="Авторы")


    class Meta():
            db_table = 'ScienceData'
            verbose_name = 'Информация о научной работе'
            verbose_name_plural = 'Информация о научных работах'


    def __str__(self):
        return f"{self.pk} - {self.title}"
    

API/views.py
from django.views.generic import ListView

from API.models import IntelForScienceWorks
from common.mixins import SearchMixin





class SearchView(ListView, SearchMixin):

    template_name = 'index.html'
    context_object_name = "information"

    def get_queryset(self):
        query = self.request.GET.get('q')
        query.strip()
        order_by = self.request.GET.get('order_by')


        worksquery = self.q_search(query)

        if order_by and order_by != "default":
            worksquery = worksquery.order_by(order_by)

        return worksquery

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = "search"
        return context

class IndexView(ListView):
    model = IntelForScienceWorks

    template_name = 'index.html'
    context_object_name = "information"

    def get_queryset(self):
        order_by = self.request.GET.get('order_by')

        information = IntelForScienceWorks.objects.all()

        if order_by and order_by != "default":
            information = information.order_by(order_by)

        return information

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = "All"
        return context
    

# def word_search(request):
#     query = request.GET.get('q')
#     order_by = request.GET.get('order_by')
    
#     query.strip()

#     # if not query:
#     #     return index(request)

#     worksquery = q_search(query)

#     if order_by and order_by != "default":
#         worksquery = worksquery.order_by(order_by)

    
#     context = {
#         'information':  worksquery,
#         'page_title': "search",
#     }

#     return render(request, "index.html", context)

# def index(request):

#     order_by = request.GET.get('order_by')

#     information = IntelForScienceWorks.objects.all()

#     if order_by and order_by != "default":
#         information = information.order_by(order_by)


#     context = {
#         'information':  information,
#         'page_title': "All",
#     }

#     return render(request, "index.html", context)

API/templates/index.html
{% load static %}


<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/styles.css" %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <title>Fsciencecheck - {{ page_title }}</title>
</head>

<body>
    <form class="d-flex flex-column" role="search" action="{% url 'main:search' %}" method="get">
    
    
    <div class="d-flex mb-2">
        <a href="{% url 'main:home' %}" class="btn btn-outline-secondary me-2">
            <i class="fas fa-home"></i>
        </a>
    
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search" {% if request.GET.q %}value="{{ request.GET.q }}{% endif %} ">
        <button class="btn btn-outline-success text-grey" type="submit">Поиск</button>
    </div>

    
    <div class="mb-3 mt-1">
        <button class="btn btn-outline-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#sortMenu" aria-controls="sortMenu">
            <i class="fas fa-sliders-h icon"></i>Сортировка
        </button>
        
    </div>

    
    <div class="offcanvas offcanvas-end custom-height" tabindex="1" id="sortMenu" aria-labelledby="sortMenuLabel">
        <div class="offcanvas-header">
            <h5 id="sortMenuLabel">Параметры сортировки</h5>
            <button type="button" class="btn-close btn-close-white text-reset" data-bs-dismiss="offcanvas" aria-label="Закрыть"></button>
        </div>
        <div class="offcanvas-body">
            
            <div class="form-check mb-3">
                <input class="form-check-input" type="radio" name="order_by" value="id" id="chkDef"=
                       {% if not request.GET.order_by or request.GET.order_by == 'id'%}checked{% endif %}>
                <label class="form-check-label" for="chkDef">По умолчанию</label>
            </div>
            <div class="form-check mb-2">
                <input class="form-check-input" type="radio" name="order_by" value="title" id="chkTitle"
                       {% if request.GET.order_by == 'title' %}checked{% endif %}>
                <label class="form-check-label" for="chkTitle">Название работы</label>
            </div>
            <div class="form-check mb-2">
                <input class="form-check-input" type="radio" name="order_by" value="annotation" id="chkAnnotation"
                       {% if request.GET.order_by == 'annotation' %}checked{% endif %}>
                <label class="form-check-label" for="chkAnnotation">Аннотация</label>
            </div>
            <div class="form-check mb-2">
                <input class="form-check-input" type="radio" name="order_by" value="year_publication" id="chkYear"
                       {% if request.GET.order_by == 'year_publication' %}checked{% endif %}>
                <label class="form-check-label" for="chkYear">Год публикации</label>
            </div>
            <div class="form-check mb-2">
                <input class="form-check-input" type="radio" name="order_by" value="OECD" id="chkOECD"
                       {% if request.GET.order_by == 'OECD' %}checked{% endif %}>
                <label class="form-check-label" for="chkOECD">OECD</label>
            </div>
            <div class="form-check mb-3">
                <input class="form-check-input" type="radio" name="order_by" value="key_words" id="chkKeywords"
                       {% if request.GET.order_by == 'key_words' %}checked{% endif %}>
                <label class="form-check-label" for="chkKeywords">Ключевые слова</label>
            </div>
        </div>
    </div>
</form>



    {% if not information and request.GET.q %}
    <div class="container">
        <h1 class="text-center mb-3 ">Ничего не найдено, попробуйте другой запрос</h1>

    {% elif request.GET.q %}
    <div class="container">
        <h1 class="text-center mb-3">Выполнен поиск по: {{request.GET.q}}</h1>
    {% else %}
    <div class="container">
        <h1 class="text-center mb-4">Полный список научных работ</h1>
    {% endif %}

        
        <div class="row">
            {% for info in  information %}
            <div class="col-lg-6 col-md-12">
                <div class="card">
                    <div class="card-header">
                        {{info.authors.full_author_name}}
                    </div>
                    <div class="card-body">
                        {% autoescape off %}
                        <h5 class="card-title">
                            {% if info.headline %} {{info.headline }}
                            {% else %} {{info.title}}
                            {% endif %}
                        </h5>
                        {% endautoescape %}
                        {% if info.annotation %}
                        <p class="card-text"><b>Аннотация</b>:{{info.annotation}}</p>
                        {% endif %}
                        <p><i class="fas fa-book icon"></i><strong>Тип работы:</strong> {{info.type_of_work.type}}</p>
                        <p><i class="fas fa-calendar icon"></i><strong>Год публикации:</strong>{{info.year_publication}}</p>
                        <p><i class="fas fa-cogs icon"></i><strong>OECD:</strong> {{info.OECD}}</p>
                        <div class="keywords">
                            {% if info.key_words %}
                            <strong>Ключевые слова:</strong>
                            <span>{{info.key_words}}</span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="card-footer">
                        {% if info.authors.other_authors %}
                        <strong><i class="fas fa-users icon"></i> Соавторы:</strong>{{info.authors.other_authors}}
                        {% endif %}
                    </div>
                </div>
            </div>

            {% endfor %}
            
        </div>
    </div>

    <script src="{% static "deps/js/jquery/jquery-3.7.0.min.js" %}"></script>
    <script src="{% static "js/bootstrap.bundle.min.js" %}"></script>
</body>
</html>